---
# tasks file for ansible-wal-g
- name: wal-g | check binary installed
  stat:
    path: "{{ walg_binary }}"
  register: walg_current_binary
  changed_when: false
  tags:
    - always

- name: wal-g | get current binary version
  shell: |
    set -o pipefail
    sudo -Hu nobody timeout 2 {{ walg_binary }} --version 2>&1 | grep -Eoi '([0-9]{1,}\.){1,3}[0-9]{1,}(|-[a-z0-9\.]{1,})' | sort -uV | head -1
  args:
    executable: /bin/bash
  register: walg_current_version
  changed_when: false
  check_mode: false
  when:
    - walg_current_binary.stat.exists
  tags:
    - always

- name: wal-g | ensure directory exists
  file:
    path: "{{ walg_binary | dirname }}"
    state: directory

- name: wal-g | ensure tmp directory exists
  file:
    path: "/tmp/wal-g-build"
    state: directory
  when:
    - not walg_current_binary.stat.exists or walg_current_version.stdout is version(walg_version, '!=')

- name: wal-g | download with unarchive when upgrade or downgrade
  unarchive:
    src: "{{ walg_url }}"
    dest: "/tmp/wal-g-build"
    exclude:
      - 'README.md'
      - 'LICENSE'
    remote_src: true
    owner: root
    group: root
    mode: 0755
  when:
    - not walg_current_binary.stat.exists or walg_current_version.stdout is version(walg_version, '!=')
    - not walg_tarball
  tags:
    - always

- name: copy tarball to server
  copy:
    src: "{{ walg_tarball }}"
    dest: /tmp/wal-g-build
  when:
    - not walg_current_binary.stat.exists or walg_current_version.stdout is version(walg_version, '!=')
    - walg_tarball | default(false)

- name: wal-g | unarchive tarball when upgrade or downgrade
  unarchive:
    src: "/tmp/wal-g-build/{{ walg_tarball | basename }}"
    dest: "/tmp/wal-g-build"
    exclude:
      - 'README.md'
      - 'LICENSE'
    remote_src: true
    owner: root
    group: root
    mode: 0755
  when:
    - not walg_current_binary.stat.exists or walg_current_version.stdout is version(walg_version, '!=')
    - walg_tarball
  tags:
    - always

- name: wal-g | move wal-g unarchived binary file to walg_binary location
  command: "mv /tmp/wal-g-build/{{ walg_archive_binary }} {{ walg_binary }}"
  when:
    - not walg_current_binary.stat.exists or walg_current_version.stdout is version(walg_version, '!=')

- name: wal-g | remove tmp directory
  file:
    path: "/tmp/wal-g-build"
    state: absent
  when:
    - not walg_current_binary.stat.exists or walg_current_version.stdout is version(walg_version, '!=')

- name: wal-g | combine env config
  block:
    - set_fact:
        walg_aws_combine: "{{ walg_aws_config | combine(walg_aws_override) }}"
    - set_fact:
        walg_azure_combine: "{{ walg_azure_config | combine(walg_azure_override) }}"
    - set_fact:
        walg_gcs_combine: "{{ walg_gcs_config | combine(walg_gcs_override) }}"
    - set_fact:
        walg_swift_combine: "{{ walg_swift_config | combine(walg_swift_override) }}"
    - set_fact:
        walg_filesystem_combine: "{{ walg_filesystem_config | combine(walg_filesystem_override) }}"
    - set_fact:
        walg_mongodb_combine: "{{ walg_mongodb_config | combine(walg_mongodb_override) }}"
    - set_fact:
        walg_mysql_combine: "{{ walg_mysql_config | combine(walg_mysql_override) }}"
    - set_fact:
        walg_postgresql_combine: "{{ walg_postgresql_config | combine(walg_postgresql_override) }}"
    - set_fact:
        walg_failover_storages_combine: "{{ walg_failover_storages_config | combine(walg_failover_storages_override) }}"
    - set_fact:
        walg_statsd_combine: "{{ walg_statsd_config | combine(walg_statsd_override) }}"
    - set_fact:
        walg_common_combine: "{{ walg_common_config | combine(walg_common_override) }}"
  tags:
    - always

- name: wal-g | check env directory
  file:
    path: "{{ walg_env | dirname }}"
    state: directory
    mode: 0755
  when: walg_conf_type == "env"
  tags:
    - always

- name: wal-g | create env file
  template:
    src: 'walg_env.j2'
    dest: "{{ walg_env }}"
    owner: root
    group: adm
    mode: 0644
  when: walg_conf_type == "env"
  tags:
    - always

- name: wal-g | remove unused env file
  file:
    path: "{{ walg_env }}"
    state: absent
  when: walg_conf_type != "env"
  tags:
    - always

- name: wal-g | check yml directory
  file:
    path: "{{ walg_conf_yml_file | dirname }}"
    state: directory
    mode: 0755
  when: walg_conf_type == "yml"
  tags:
    - always

- name: wal-g | create yml file
  template:
    src: 'config.yml.j2'
    dest: "{{ walg_conf_yml_file }}"
    owner: root
    group: adm
    mode: 0644
  when: walg_conf_type == "yml"
  tags:
    - always

- name: wal-g | remove unused yaml conf file
  file:
    path: "{{ walg_conf_yml_file }}"
    state: absent
  when: walg_conf_type != "yml"
  tags:
    - always

- name: wal-g | check scripts directory
  file:
    path: "{{ walg_script_path }}"
    state: directory
    mode: 0755
  tags:
    - always

- name: wal-g | create scripts files
  template:
    src: "{{ item }}"
    dest: "{{ walg_script_path }}/{{ item | basename | regex_replace('.j2','') }}"
    backup: no
    owner: root
    group: adm
    mode: 0755
  with_fileglob:
    - ../templates/*.sh.j2
  tags:
    - always

- name: wal-g | create cron job for create backups
  cron:
    name: Create wal-g backups
    hour: '1'
    minute: '0'
    user: "{{ walg_user }}"
    job: "{{ walg_script_path }}/walg-backup.sh"
    state: "{{ walg_cron_enabled | ternary('present', 'absent') }}"
  tags:
    - always

- name: wal-g | create cron job for rotate backups
  cron:
    name: Rotate wal-g backups
    hour: '0'
    minute: '0'
    user: "{{ walg_user }}"
    job: "{{ walg_script_path }}/walg-rotate.sh"
    state: "{{ walg_cron_enabled | ternary('present', 'absent') }}"
  tags:
    - always
